win32:
	vs2010x86_build.bat

linux:
	chmod a+x ./gnu_build.sh
	sh ./gnu_build.sh

mac:
	chmod a+x ./xcode_build.sh
	sh ./xcode_build.sh

cp-unix:
	chmod a+x ./cp_unix.sh
	sh ./cp_unix.sh

cp-win32:
	cp_win32.bat